/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;

/**
 *
 * @author l2001
 */
public class CalculadoraVista extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraVista
     */
    public CalculadoraVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelMatrizUno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        matrizUno = new javax.swing.JTable();
        panelMatrizDos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        matrizDos = new javax.swing.JTable();
        panelMatrizResultante = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        matrizResultante = new javax.swing.JTable();
        botonMultiplicacion = new javax.swing.JButton();
        labelMatrizDos = new javax.swing.JLabel();
        labelMatrizResultante = new javax.swing.JLabel();
        labelMatrizUno = new javax.swing.JLabel();
        botonSuma = new javax.swing.JButton();
        botonTranspuesta = new javax.swing.JButton();
        botonInversa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        textNota = new javax.swing.JTextArea();
        botonSistema = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textEscalar = new javax.swing.JTextArea();
        botonMultiplicacionEscalar = new javax.swing.JButton();
        botonDeterminante = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonSistemaCramer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);

        panelPrincipal.setBackground(new java.awt.Color(54, 57, 63));

        panelMatrizUno.setBackground(new java.awt.Color(153, 170, 181));
        panelMatrizUno.setPreferredSize(new java.awt.Dimension(350, 350));

        matrizUno.setBackground(new java.awt.Color(153, 170, 181));
        matrizUno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        matrizUno.setForeground(new java.awt.Color(255, 255, 255));
        matrizUno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        matrizUno.setGridColor(new java.awt.Color(0, 0, 0));
        matrizUno.setRowHeight(50);
        matrizUno.setRowSelectionAllowed(false);
        matrizUno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(matrizUno);
        if (matrizUno.getColumnModel().getColumnCount() > 0) {
            matrizUno.getColumnModel().getColumn(0).setResizable(false);
            matrizUno.getColumnModel().getColumn(1).setResizable(false);
            matrizUno.getColumnModel().getColumn(2).setResizable(false);
            matrizUno.getColumnModel().getColumn(3).setResizable(false);
            matrizUno.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelMatrizUnoLayout = new javax.swing.GroupLayout(panelMatrizUno);
        panelMatrizUno.setLayout(panelMatrizUnoLayout);
        panelMatrizUnoLayout.setHorizontalGroup(
            panelMatrizUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizUnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMatrizUnoLayout.setVerticalGroup(
            panelMatrizUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatrizUnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        panelMatrizDos.setBackground(new java.awt.Color(153, 170, 181));
        panelMatrizDos.setPreferredSize(new java.awt.Dimension(350, 350));

        matrizDos.setBackground(new java.awt.Color(153, 170, 181));
        matrizDos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        matrizDos.setForeground(new java.awt.Color(255, 255, 255));
        matrizDos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Igualdad", "-", "-", "-", "-"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        matrizDos.setGridColor(new java.awt.Color(0, 0, 0));
        matrizDos.setRowHeight(50);
        matrizDos.setRowSelectionAllowed(false);
        matrizDos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(matrizDos);
        if (matrizDos.getColumnModel().getColumnCount() > 0) {
            matrizDos.getColumnModel().getColumn(0).setResizable(false);
            matrizDos.getColumnModel().getColumn(1).setResizable(false);
            matrizDos.getColumnModel().getColumn(2).setResizable(false);
            matrizDos.getColumnModel().getColumn(3).setResizable(false);
            matrizDos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelMatrizDosLayout = new javax.swing.GroupLayout(panelMatrizDos);
        panelMatrizDos.setLayout(panelMatrizDosLayout);
        panelMatrizDosLayout.setHorizontalGroup(
            panelMatrizDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizDosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMatrizDosLayout.setVerticalGroup(
            panelMatrizDosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatrizDosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        panelMatrizResultante.setBackground(new java.awt.Color(153, 170, 181));
        panelMatrizResultante.setPreferredSize(new java.awt.Dimension(350, 350));

        matrizResultante.setBackground(new java.awt.Color(153, 170, 181));
        matrizResultante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        matrizResultante.setForeground(new java.awt.Color(255, 255, 255));
        matrizResultante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "X1", "X2", "X3", "X4", "X5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        matrizResultante.setEnabled(false);
        matrizResultante.setGridColor(new java.awt.Color(0, 0, 0));
        matrizResultante.setRowHeight(50);
        matrizResultante.setRowSelectionAllowed(false);
        matrizResultante.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(matrizResultante);
        if (matrizResultante.getColumnModel().getColumnCount() > 0) {
            matrizResultante.getColumnModel().getColumn(0).setResizable(false);
            matrizResultante.getColumnModel().getColumn(1).setResizable(false);
            matrizResultante.getColumnModel().getColumn(2).setResizable(false);
            matrizResultante.getColumnModel().getColumn(3).setResizable(false);
            matrizResultante.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout panelMatrizResultanteLayout = new javax.swing.GroupLayout(panelMatrizResultante);
        panelMatrizResultante.setLayout(panelMatrizResultanteLayout);
        panelMatrizResultanteLayout.setHorizontalGroup(
            panelMatrizResultanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMatrizResultanteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMatrizResultanteLayout.setVerticalGroup(
            panelMatrizResultanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMatrizResultanteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        botonMultiplicacion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonMultiplicacion.setText("A x B");
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });

        labelMatrizDos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMatrizDos.setForeground(new java.awt.Color(255, 255, 255));
        labelMatrizDos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMatrizDos.setText("Matriz Dos (B)");

        labelMatrizResultante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMatrizResultante.setForeground(new java.awt.Color(255, 255, 255));
        labelMatrizResultante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMatrizResultante.setText("Matriz Resultante");

        labelMatrizUno.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelMatrizUno.setForeground(new java.awt.Color(255, 255, 255));
        labelMatrizUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMatrizUno.setText("Matriz Uno (A)");

        botonSuma.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonSuma.setText("A + B");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });

        botonTranspuesta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonTranspuesta.setText("Transpuesta");
        botonTranspuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTranspuestaActionPerformed(evt);
            }
        });

        botonInversa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonInversa.setText("Inversa");
        botonInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInversaActionPerformed(evt);
            }
        });

        textNota.setEditable(false);
        textNota.setBackground(new java.awt.Color(54, 57, 63));
        textNota.setColumns(20);
        textNota.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textNota.setForeground(new java.awt.Color(255, 255, 255));
        textNota.setRows(5);
        textNota.setText("Nota:\nLos encabezados solo se toman en cuenta\npara resolver sistemas de ecuaciones.\nNo es necesario llenar los 5 campos.");
        textNota.setAutoscrolls(false);
        textNota.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        textNota.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textNota.setFocusable(false);
        textNota.setMargin(new java.awt.Insets(0, 0, 0, 0));
        textNota.setSelectedTextColor(new java.awt.Color(255, 102, 102));
        jScrollPane4.setViewportView(textNota);

        botonSistema.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonSistema.setText("Sistema Gauss");
        botonSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSistemaActionPerformed(evt);
            }
        });

        textEscalar.setColumns(3);
        textEscalar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textEscalar.setRows(1);
        textEscalar.setTabSize(1);
        textEscalar.setMinimumSize(new java.awt.Dimension(3, 0));
        jScrollPane5.setViewportView(textEscalar);

        botonMultiplicacionEscalar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonMultiplicacionEscalar.setText("A x E");
        botonMultiplicacionEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionEscalarActionPerformed(evt);
            }
        });

        botonDeterminante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonDeterminante.setText("Determinante");
        botonDeterminante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDeterminanteActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLimpiar.setText("Borrar Datos");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonSistemaCramer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonSistemaCramer.setText("Sistema Cramer");
        botonSistemaCramer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSistemaCramerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMatrizUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatrizUno, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonTranspuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonDeterminante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMultiplicacionEscalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addGap(65, 65, 65)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(labelMatrizDos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelMatrizResultante, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelMatrizDos, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(botonSuma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(botonMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonSistemaCramer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(panelMatrizResultante, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))))
                .addGap(55, 55, 55))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMatrizDos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatrizResultante, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMatrizUno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMatrizResultante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMatrizDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMatrizUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSuma)
                            .addComponent(botonSistema))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonSistemaCramer)
                            .addComponent(botonMultiplicacion)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(botonTranspuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonInversa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonDeterminante))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMultiplicacionEscalar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(botonLimpiar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonTranspuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTranspuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTranspuestaActionPerformed

    private void botonInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInversaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInversaActionPerformed

    private void botonSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSistemaActionPerformed

    private void botonMultiplicacionEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionEscalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMultiplicacionEscalarActionPerformed

    private void botonDeterminanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDeterminanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDeterminanteActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonSistemaCramerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSistemaCramerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSistemaCramerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraVista().setVisible(true);
            }
        });
        
        
        
    }

    public JButton getBotonDeterminante() {
        return botonDeterminante;
    }

    public void setBotonDeterminante(JButton botonDeterminante) {
        this.botonDeterminante = botonDeterminante;
    }

    public JButton getBotonInversa() {
        return botonInversa;
    }

    public void setBotonInversa(JButton botonInversa) {
        this.botonInversa = botonInversa;
    }

    public JButton getBotonMultiplicacion() {
        return botonMultiplicacion;
    }

    public void setBotonMultiplicacion(JButton botonMultiplicacion) {
        this.botonMultiplicacion = botonMultiplicacion;
    }

    public JButton getBotonMultiplicacionEscalar() {
        return botonMultiplicacionEscalar;
    }

    public void setBotonMultiplicacionEscalar(JButton botonMultiplicacionEscalar) {
        this.botonMultiplicacionEscalar = botonMultiplicacionEscalar;
    }

    public JButton getBotonSistema() {
        return botonSistema;
    }

    public void setBotonSistema(JButton botonSistema) {
        this.botonSistema = botonSistema;
    }

    public JButton getBotonSuma() {
        return botonSuma;
    }

    public void setBotonSuma(JButton botonSuma) {
        this.botonSuma = botonSuma;
    }

    public JButton getBotonTranspuesta() {
        return botonTranspuesta;
    }

    public void setBotonTranspuesta(JButton botonTranspuesta) {
        this.botonTranspuesta = botonTranspuesta;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JScrollPane getjScrollPane4() {
        return jScrollPane4;
    }

    public void setjScrollPane4(JScrollPane jScrollPane4) {
        this.jScrollPane4 = jScrollPane4;
    }

    public JScrollPane getjScrollPane5() {
        return jScrollPane5;
    }

    public void setjScrollPane5(JScrollPane jScrollPane5) {
        this.jScrollPane5 = jScrollPane5;
    }

    public JLabel getLabelMatrizDos() {
        return labelMatrizDos;
    }

    public void setLabelMatrizDos(JLabel labelMatrizDos) {
        this.labelMatrizDos = labelMatrizDos;
    }

    public JLabel getLabelMatrizResultante() {
        return labelMatrizResultante;
    }

    public void setLabelMatrizResultante(JLabel labelMatrizResultante) {
        this.labelMatrizResultante = labelMatrizResultante;
    }

    public JLabel getLabelMatrizUno() {
        return labelMatrizUno;
    }

    public void setLabelMatrizUno(JLabel labelMatrizUno) {
        this.labelMatrizUno = labelMatrizUno;
    }

    public JTable getMatrizDos() {
        return matrizDos;
    }

    public void setMatrizDos(JTable matrizDos) {
        this.matrizDos = matrizDos;
    }

    public JTable getMatrizResultante() {
        return matrizResultante;
    }

    public void setMatrizResultante(JTable matrizResultante) {
        this.matrizResultante = matrizResultante;
    }

    public JTable getMatrizUno() {
        return matrizUno;
    }

    public void setMatrizUno(JTable matrizUno) {
        this.matrizUno = matrizUno;
    }

    public JPanel getPanelMatrizDos() {
        return panelMatrizDos;
    }

    public void setPanelMatrizDos(JPanel panelMatrizDos) {
        this.panelMatrizDos = panelMatrizDos;
    }

    public JPanel getPanelMatrizResultante() {
        return panelMatrizResultante;
    }

    public void setPanelMatrizResultante(JPanel panelMatrizResultante) {
        this.panelMatrizResultante = panelMatrizResultante;
    }

    public JPanel getPanelMatrizUno() {
        return panelMatrizUno;
    }

    public void setPanelMatrizUno(JPanel panelMatrizUno) {
        this.panelMatrizUno = panelMatrizUno;
    }

    public JPanel getPanelPrincipal() {
        return panelPrincipal;
    }

    public void setPanelPrincipal(JPanel panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }

    public JTextArea getTextEscalar() {
        return textEscalar;
    }

    public void setTextEscalar(JTextArea textEscalar) {
        this.textEscalar = textEscalar;
    }

    public JTextArea getTextNota() {
        return textNota;
    }

    public void setTextNota(JTextArea textNota) {
        this.textNota = textNota;
    }

    public JButton getBotonLimpiar() {
        return botonLimpiar;
    }

    public void setBotonLimpiar(JButton botonLimpiar) {
        this.botonLimpiar = botonLimpiar;
    }

    public JButton getBotonSistemaCramer() {
        return botonSistemaCramer;
    }

    public void setBotonSistemaCramer(JButton botonSistemaCramer) {
        this.botonSistemaCramer = botonSistemaCramer;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDeterminante;
    private javax.swing.JButton botonInversa;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonMultiplicacionEscalar;
    private javax.swing.JButton botonSistema;
    private javax.swing.JButton botonSistemaCramer;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonTranspuesta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelMatrizDos;
    private javax.swing.JLabel labelMatrizResultante;
    private javax.swing.JLabel labelMatrizUno;
    private javax.swing.JTable matrizDos;
    private javax.swing.JTable matrizResultante;
    private javax.swing.JTable matrizUno;
    private javax.swing.JPanel panelMatrizDos;
    private javax.swing.JPanel panelMatrizResultante;
    private javax.swing.JPanel panelMatrizUno;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextArea textEscalar;
    private javax.swing.JTextArea textNota;
    // End of variables declaration//GEN-END:variables
}
